name: Validate ALB Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  validate-alb:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 🎯 Validate ALB Deployment
        run: |
          chmod +x validate-alb-deployment.sh
          ./validate-alb-deployment.sh
